name: Dependency scan

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle Dependency Submission
        uses: mikepenz/gradle-dependency-submission@main
        with:
          gradle-build-module: |-
            :server
            :client:rest
          gradle-build-configuration: |-
            compileClasspath
          sub-module-mode: INDIVIDUAL
